name: PlatformIO CI new
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: 
          - logic_1_0
          - logic_1_1
          - logic_2_0
        example: 
          - _TEMPLATE
          - buttons
          - buttons-leds
          - buzzer
          - cteni_souboru
          - display
          - game-pong
          - game-simon
          - graphics_01_generativeDesign
          - graphics_02_fire
          - graphics_03_knight_rider
          - network-room
          - rbcontoller-basic
          - sachovnice
          - snake_01_dot_move
          - snake_01_dot_move_infin
          - snake_02_dot_change_direction
          - snake_03_tail
          - statusBar
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO examples
        run: pio ci -e ${{ matrix.environment }} -l"." -c ${{ matrix.example }}/platformio.ini
        env:
          PLATFORMIO_CI_SRC: examples/${{ matrix.example }}/src
          PLATFORMIO_BUILD_FLAGS: -Iexamples/${{ matrix.example }}/include
