name: PlatformIO CI new
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment:
          - logic_1_1
          - logic_1_2
          - logic_2_0
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      - name: Build examples
        run: ./build_examples.sh ${{ matrix.environment }}
